name             'cb-platform'
maintainer       'Stephen Van Zee'
maintainer_email 'svanzee@caringbridge.org'
license          'All rights reserved'
description      'Installs/Configures cb-platform'
long_description 'Installs/Configures cb-platform'
version          '0.1.0'
